version: '3.9'

services:
  user-service:
    build: ./microservices/user-service
    ports:
      - "5000:5000"

  product-service:
    build: ./microservices/product-service
    ports:
      - "8081:8081"