pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t product-service-image ./microservices/product-service'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -d -p 8081:8081 --name product-service-run product-service-image || true'
            }
        }
    }
}
