pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dockerImage = docker.build("product-service-image")
                }
            }
        }

        stage('Run Container') {
            steps {
                script {
                    dockerImage.run('-p 8081:8081')
                }
            }
        }
    }
}