pipeline {
    agent {
        docker {
            image 'docker:24.0.7-dind'
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    stages {
        stage('Build Image') {
            steps {
                sh 'docker build -t product-service-image ./microservices/product-service'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -d -p 8081:8081 --name product-service-run product-service-image || true'
            }
        }
    }
}
